x-variables:
  - &DB_HOST "db"
  - &DB_ROOT_PASSWORD "db"
  - &DB_DATABASE "marktwerking"
  - &DB_USERNAME "dbuser"
  - &DB_PASSWORD "dbpass"
  - &MW_ADMIN_PASSWORD "MW23"
  - &NETWORK_SUBNET "192.168.31.0/29"
  - &MW_DEBUG "True"

  
services:

  #phpmyadmin
  marktwerking.pma:
    container_name: marktwerking.pma
    hostname: pma
    image: ghcr.io/linuxserver/phpmyadmin
#    profiles:
#      - debug
    environment:
      PMA_HOST: *DB_HOST
      PMA_USER: root
      PMA_PASSWORD: *DB_ROOT_PASSWORD
      TZ: Europe/Amsterdam
    ports: 
      - 4081:80
    restart: unless-stopped
    networks:
      - net

  #MySQL Service
  marktwerking.db:
    hostname: db
    container_name: marktwerking.db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: *DB_ROOT_PASSWORD
      MYSQL_DATABASE: *DB_DATABASE
      MYSQL_USER: *DB_USERNAME
      MYSQL_PASSWORD: *DB_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
    volumes_from:
      - marktwerking.php:ro
    networks:
      - net
    restart: always

  #PHP Service
  marktwerking.php:
    hostname: php
    image: ghcr.io/vslcatena/marktwerking/docker-marktwerking:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: marktwerking.php
    environment:
      MW_DB_HOST: *DB_HOST
      MW_DB_USERNAME: *DB_USERNAME
      MW_DB_PASSWORD: *DB_PASSWORD
      MW_DB_DATABASE: *DB_DATABASE
      MW_BAR_PASSWORD: *MW_ADMIN_PASSWORD
      MW_IP_WHITELIST: 192.168.4.0/24,192.168.40.0/24
      MW_DEBUG: *MW_DEBUG
      TITLE: Marktwerking 2023
    tty: true
    ports:
      - 4080:80
    networks:
      - net

#Docker Networks
networks:
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: *NETWORK_SUBNET
    driver_opts:
     com.docker.network.bridge.name: marktw_net
volumes:
  dbdata:
    driver: local
